service: remak-scrap
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-2
  timeout: 300
  memorySize: 2048
  environment:
    NODE_ENV: 'production'
    DB_URL: ${env:DB_URL}
    SQS_URL: ${env:SQS_URL}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:*"
        - "ec2:CreateNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:DeleteNetworkInterface"
        - "sqs:SendMessage"
        - "sqs:GetQueueUrl"
        - "sqs:ListQueues"
      Resource: "*"
  logRetentionInDays: 14
  layers:
    - arn:aws:lambda:ap-northeast-2:518272060765:layer:chromium:6

functions:
  remak-scraping:
    handler: src/handler.handler

constructs:
  remak-scraping-queue:
    type: queue
    worker:
      handler: src/handler.handler
      maxConcurrency: 50
      timeout: 600

plugins:
  - serverless-dotenv-plugin
  - serverless-lift
  - serverless-plugin-typescript
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 10
