export const lambdaBrowserArgs = JSON.stringify([
  '--disable-domain-reliability',
  '--disable-print-preview',
  '--disable-speech-api',
  '--disk-cache-size=33554432',
  '--mute-audio',
  '--no-default-browser-check',
  // '--no-pings', //single-file-cli에서 기본으로 포함됨
  '--single-process',

  '--hide-scrollbars',
  '--ignore-gpu-blocklist',
  '--in-process-gpu',

  '--allow-running-insecure-content',
  '--disable-setuid-sandbox',
  '--disable-site-isolation-trials',
  '--disable-web-security',
  '--no-sandbox',
  '--no-zygote',
]);

export const defaultSingleFileArgs = {
  // userAgent:
  //   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36',
  filenameConflictAction: 'overwrite',
  acceptHeaders: {
    font: 'application/font-woff2;q=1.0,application/font-woff;q=0.9,*/*;q=0.8',
    image: 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8',
    stylesheet: 'text/css,*/*;q=0.1',
    script: '*/*',
    document: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
  },
  backEnd: 'puppeteer',
  blockMixedContent: false,
  browserServer: '',
  browserHeadless: true,
  browserWidth: 1920,
  browserHeight: 1080,
  browserLoadMaxTime: 60000,
  browserWaitDelay: 0,
  browserWaitUntil: 'networkidle0',
  browserWaitUntilFallback: true,
  browserDebug: false,
  browserStartMinimized: false,
  browserCookiesFile: '',
  browserIgnoreInsecureCerts: true,
  browserFreezePrototypes: false,
  dumpContent: false,
  filenameTemplate: '{page-title} ({date-iso} {time-locale}).html',
  filenameReplacementCharacter: '_',
  filenameMaxLength: 192,
  filenameMaxLengthUnit: 'bytes',
  replaceEmojisInFilename: false,
  groupDuplicateImages: true,
  maxSizeDuplicateImages: 524288,
  httpProxyServer: '',
  httpProxyUsername: '',
  httpProxyPassword: '',
  includeInfobar: false,
  insertMetaCsp: true,
  loadDeferredImages: true,
  loadDeferredImagesDispatchScrollEvent: false,
  loadDeferredImagesMaxIdleTime: 1500,
  loadDeferredImagesKeepZoomLevel: false,
  loadDeferredImagesBeforeFrames: false,
  maxParallelWorkers: 8,
  maxResourceSizeEnabled: false,
  maxResourceSize: 10,
  moveStylesInHead: false,
  outputDirectory: '',
  removeHiddenElements: true,
  removeUnusedStyles: true,
  removeUnusedFonts: true,
  removeSavedDate: false,
  removeFrames: false,
  blockScripts: true,
  blockAudios: true,
  blockVideos: true,
  removeAlternativeFonts: true,
  removeAlternativeMedias: true,
  removeAlternativeImages: true,
  saveOriginalUrls: false,
  saveRawPage: false,
  webDriverExecutablePath: '',
  userScriptEnabled: true,
  crawlLinks: false,
  crawlInnerLinksOnly: true,
  crawlRemoveUrlFragment: true,
  crawlMaxDepth: 1,
  crawlExternalLinksMaxDepth: 1,
  crawlReplaceUrls: false,
  backgroundSave: true,
  crawlReplaceURLs: false,
  crawlRemoveURLFragment: true,
  insertMetaCSP: true,
  saveOriginalURLs: false,
  httpHeaders: {
    'Accept-Language': 'ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7',
  },
  browserCookies: [],
  browserScripts: [],
  browserStylesheets: [],
  crawlRewriteRules: [],
  emulateMediaFeatures: [],
  retrieveLinks: true,

  compressHTML: false,
};
